export type LeadStatus = "Novo" | "Aguardando contato" | "Contatado" | "Aguardando resposta" | "Interessado" | "Negociação" | "Proposta enviada" | "Cliente fechado" | "Recusado" | "Não contatar" | "Sem resposta";
export type Session = {access_token:string;refresh_token:string;expires_at?:number;user:{id:string;email?:string}};
export type Lead = {id:string;user_id:string;provider_place_id:string;company_name:string;country:string|null;region:string|null;city:string|null;category:string|null;address:string|null;phone:string|null;website:string|null;status:LeadStatus;notes:string|null;opportunity_score:number|null;opportunity_confidence:string|null;last_contact_at:string|null;created_at:string;updated_at:string};
export type PlaceResult = {place_id:string;name:string;country:string;region:string|null;city:string|null;category:string|null;address:string|null;phone:string|null;website:string|null;rating:number|null;rating_count:number|null;maps_url:string|null};
type Result<T>={data?:T;error?:string};
const URL=(import.meta.env.VITE_SUPABASE_URL as string|undefined)?.replace(/\/$/,"")??"";
const ANON=(import.meta.env.VITE_SUPABASE_ANON_KEY as string|undefined)??"";
const KEY="simply-connect-session";\nlet placesReady=false;
function err(body:any):string{const msg=String(body?.msg??body?.message??body?.error_description??body?.error??"Ocorreu um erro inesperado.");if(/Invalid login credentials/i.test(msg))return "E-mail ou senha incorretos.";if(/Email not confirmed/i.test(msg))return "Confirme seu e-mail antes de entrar.";if(/User already registered/i.test(msg))return "Já existe uma conta com esse e-mail.";return msg}
export const backend={
 configured:()=>Boolean(URL&&ANON),
 placesConfigured:()=>placesReady,
 session():Session|null{if(typeof window==="undefined")return null;try{const raw=localStorage.getItem(KEY);if(!raw)return null;const s=JSON.parse(raw) as Session;if(s.expires_at&&s.expires_at*1000<Date.now()+30000){localStorage.removeItem(KEY);return null}return s}catch{return null}},
 async authenticate(mode:"login"|"signup",email:string,password:string):Promise<Result<Session>>{try{const endpoint=mode==="login"?"token?grant_type=password":"signup";const res=await fetch(URL+"/auth/v1/"+endpoint,{method:"POST",headers:{"Content-Type":"application/json",apikey:ANON},body:JSON.stringify({email,password})});const body=await res.json();if(!res.ok)return{error:err(body)};if(!body.access_token||!body.user?.id)return{error:"Conta criada. Se a confirmação de e-mail estiver habilitada, confirme o endereço antes de entrar."};const s:Session={access_token:body.access_token,refresh_token:body.refresh_token,expires_at:Math.floor(Date.now()/1000)+Number(body.expires_in??3600),user:body.user};localStorage.setItem(KEY,JSON.stringify(s));return{data:s}}catch{return{error:"Não foi possível conectar ao Supabase. Verifique as configurações."}}},
 signOut(){if(typeof window!=="undefined")localStorage.removeItem(KEY)},
 async request<T>(path:string,init:RequestInit={}):Promise<Result<T>>{const s=this.session();if(!s)return{error:"Sua sessão expirou. Entre novamente."};try{const res=await fetch(URL+"/rest/v1/"+path,{...init,headers:{apikey:ANON,Authorization:"Bearer "+s.access_token,"Content-Type":"application/json",...(init.headers??{})}});const text=await res.text();const body=text?JSON.parse(text):null;if(!res.ok)return{error:err(body)};return{data:body as T}}catch{return{error:"Falha de conexão ao consultar o banco. Tente novamente."}}},
 getLeads():Promise<Result<Lead[]>>{return this.request<Lead[]>("leads?select=*&archived_at=is.null&order=created_at.desc&limit=500")},
 async saveLead(p:PlaceResult):Promise<Result<Lead>>{const s=this.session();if(!s)return{error:"Entre novamente para salvar o lead."};const r=await this.request<Lead[]>("leads?on_conflict=user_id,provider_place_id",{method:"POST",headers:{Prefer:"resolution=ignore-duplicates,return=representation"},body:JSON.stringify({user_id:s.user.id,provider_place_id:p.place_id,company_name:p.name,country:p.country,region:p.region,city:p.city,category:p.category,address:p.address,phone:p.phone,website:p.website,source:"google_places",status:"Novo"})});if(r.error)return{error:r.error};if(!r.data?.[0])return{error:"Esta empresa já está salva no CRM."};return{data:r.data[0]}},
 updateLead(id:string,patch:Partial<Pick<Lead,"status"|"notes"|"last_contact_at"|"website"|"phone"|"opportunity_score"|"opportunity_confidence">>):Promise<Result<Lead[]>>{return this.request<Lead[]>("leads?id=eq."+encodeURIComponent(id)+"&select=*",{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(patch)})},
 async searchPlaces(filters:{country:string;region:string;city:string;niche:string;websiteFilter:string}):Promise<Result<PlaceResult[]>>{const s=this.session();if(!s)return{error:"Entre novamente para pesquisar empresas."};try{const res=await fetch(URL+"/functions/v1/search-places",{method:"POST",headers:{"Content-Type":"application/json",apikey:ANON,Authorization:"Bearer "+s.access_token},body:JSON.stringify(filters)});const body=await res.json();if(!res.ok)return{error:err(body)};placesReady=true;return{data:(body.results??[]) as PlaceResult[]}}catch{return{error:"Falha ao acessar o serviço de busca. Verifique se a Edge Function foi publicada."}}}
};
