import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import { Activity, ArrowRight, Building2, Check, ChevronDown, CircleHelp, Command, ExternalLink, Globe2, LayoutDashboard, LoaderCircle, LogOut, MapPin, Menu, MessageCircle, Plus, RefreshCw, Search, Settings2, ShieldCheck, Target, Users, X } from "lucide-react";
import { backend, type Lead, type LeadStatus, type PlaceResult } from "../lib/backend";

export const Route = createFileRoute("/")({ component: Index });
type Page = "overview" | "search" | "leads" | "opportunities" | "pipeline" | "history" | "settings";
const nav: {id:Page;label:string;icon:typeof LayoutDashboard}[] = [
 {id:"overview",label:"Visão geral",icon:LayoutDashboard},{id:"search",label:"Buscar empresas",icon:Search},{id:"leads",label:"Meus leads",icon:Building2},{id:"opportunities",label:"Oportunidades",icon:Target},{id:"pipeline",label:"Pipeline comercial",icon:Activity},{id:"history",label:"Histórico",icon:RefreshCw},{id:"settings",label:"Configurações",icon:Settings2}
];
const statuses:LeadStatus[]=["Novo","Aguardando contato","Contatado","Aguardando resposta","Interessado","Negociação","Proposta enviada","Cliente fechado","Recusado","Não contatar","Sem resposta"];
function Index(){
 const [page,setPage]=useState<Page>("overview"),[mobileNav,setMobileNav]=useState(false),[session,setSession]=useState(backend.session());
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[authMode,setAuthMode]=useState<"login"|"signup">("login"),[authBusy,setAuthBusy]=useState(false),[authError,setAuthError]=useState("");
 const [leads,setLeads]=useState<Lead[]>([]),[loading,setLoading]=useState(false),[notice,setNotice]=useState("");
 const [city,setCity]=useState(""),[region,setRegion]=useState(""),[country,setCountry]=useState("Brasil"),[niche,setNiche]=useState("Barbearias"),[customNiche,setCustomNiche]=useState(""),[websiteFilter,setWebsiteFilter]=useState("all");
 const [results,setResults]=useState<PlaceResult[]>([]),[searchBusy,setSearchBusy]=useState(false),[searchError,setSearchError]=useState(""),[savingId,setSavingId]=useState(""),[query,setQuery]=useState(""),[statusFilter,setStatusFilter]=useState("Todos"),[selected,setSelected]=useState<Lead|null>(null);
 async function loadLeads(){if(!session)return;setLoading(true);const r=await backend.getLeads();if(r.error)setNotice(r.error);else setLeads(r.data??[]);setLoading(false)}
 useEffect(()=>{if(session)void loadLeads()},[session]);
 async function auth(e:FormEvent){e.preventDefault();setAuthBusy(true);setAuthError("");const r=await backend.authenticate(authMode,email,password);if(r.error)setAuthError(r.error);else setSession(backend.session());setAuthBusy(false)}
 async function search(e:FormEvent){e.preventDefault();setSearchError("");setResults([]);if(!city.trim()||!(niche==="Outro nicho"?customNiche:niche).trim()){setSearchError("Informe uma cidade e um nicho.");return}setSearchBusy(true);const r=await backend.searchPlaces({country,region,city,niche:niche==="Outro nicho"?customNiche:niche,websiteFilter});if(r.error)setSearchError(r.error);else setResults(r.data??[]);setSearchBusy(false)}
 async function save(p:PlaceResult){if(leads.some(l=>l.provider_place_id===p.place_id)){setNotice("Esta empresa já está salva.");return}setSavingId(p.place_id);const r=await backend.saveLead(p);if(r.error)setNotice(r.error);else{setLeads(old=>[r.data!,...old]);setNotice("Empresa salva no CRM.")}setSavingId("")}
 async function changeStatus(lead:Lead,status:LeadStatus){const old=leads;setLeads(cur=>cur.map(l=>l.id===lead.id?{...l,status}:l));const r=await backend.updateLead(lead.id,{status});if(r.error){setLeads(old);setNotice(r.error)}else{setNotice("Status atualizado.");setSelected(cur=>cur?.id===lead.id?{...cur,status}:cur)}}
 const title=nav.find(n=>n.id===page)?.label??"Visão geral";
 const shownLeads=leads.filter(l=>(!query||[l.company_name,l.city,l.category,l.phone].some(v=>(v??"").toLowerCase().includes(query.toLowerCase())))&&(statusFilter==="Todos"||l.status===statusFilter)&&(page!=="opportunities"||(l.opportunity_score??0)>=50));
 const counts={total:leads.length,new:leads.filter(l=>["Novo","Aguardando contato"].includes(l.status)).length,contacted:leads.filter(l=>["Contatado","Aguardando resposta"].includes(l.status)).length,active:leads.filter(l=>["Interessado","Negociação","Proposta enviada"].includes(l.status)).length,closed:leads.filter(l=>l.status==="Cliente fechado").length};
 if(!backend.configured())return <Setup/>;
 if(!session)return <div className="auth-shell"><form className="auth-card" onSubmit={auth}><Brand/><span className="eyebrow">WORKSPACE B2B</span><h1>{authMode==="login"?"Entre no Simply Connect":"Crie seu workspace"}</h1><p className="muted">Organize sua prospecção e acompanhe oportunidades comerciais.</p><label>E-mail<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@empresa.com"/></label><label>Senha<input type="password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mínimo de 8 caracteres"/></label>{authError&&<div className="alert">{authError}</div>}<button className="btn primary full" disabled={authBusy}>{authBusy&&<LoaderCircle className="spin" size={16}/>}{authMode==="login"?"Entrar":"Criar conta"}<ArrowRight size={16}/></button><p className="auth-switch">{authMode==="login"?"Ainda não tem conta?":"Já tem conta?"} <button type="button" onClick={()=>setAuthMode(authMode==="login"?"signup":"login")}>{authMode==="login"?"Criar conta":"Entrar"}</button></p><p className="tiny muted">Autenticação Supabase. Seus dados são isolados por usuário.</p></form></div>;
 return <div className="app-shell"><aside className={"sidebar "+(mobileNav?"mobile-open":"")}><div className="brand-row"><Brand/><button className="icon-btn mobile-close" onClick={()=>setMobileNav(false)}><X size={18}/></button></div><div className="workspace-switch"><div className="workspace-mark">S</div><div className="workspace-copy"><strong>Meu workspace</strong><span>Plano inicial</span></div><ChevronDown size={15}/></div><div className="nav-caption">WORKSPACE</div><nav className="side-nav">{nav.map(n=>{const I=n.icon;return <button key={n.id} className={"nav-item "+(page===n.id?"active":"")} onClick={()=>{setPage(n.id);setMobileNav(false);setNotice("")}}><I size={17}/><span>{n.label}</span>{n.id==="leads"&&leads.length>0&&<span className="nav-count">{leads.length}</span>}</button>})}</nav><div className="sidebar-bottom"><div className="usage-card"><strong>Seu workspace</strong><p>Conecte as integrações para desbloquear a prospecção real.</p><span className={"integration-status "+(backend.placesConfigured()?"connected":"pending")}>{backend.placesConfigured()?"Supabase configurado":"Verifique as integrações"}</span></div><button className="profile-row" onClick={()=>{backend.signOut();setSession(null);setLeads([])}}><div className="avatar">{(session.user.email??"U").slice(0,1).toUpperCase()}</div><div className="profile-copy"><strong>{session.user.email}</strong><span>Conta autenticada</span></div><LogOut size={15}/></button></div></aside>{mobileNav&&<button className="mobile-backdrop" onClick={()=>setMobileNav(false)}/>}<main className="main-area"><header className="topbar"><div className="topbar-left"><button className="icon-btn mobile-menu" onClick={()=>setMobileNav(true)}><Menu size={20}/></button><div className="breadcrumbs"><span>Workspace</span><span>/</span><strong>{title}</strong></div></div><div className="topbar-actions"><span className="connection-pill"><i/>Supabase</span><button className="icon-btn" onClick={()=>setNotice("As integrações e variáveis de ambiente estão em Configurações.")}><CircleHelp size={17}/></button></div></header><div className="page-content">{notice&&<div className="notice">{notice}<button onClick={()=>setNotice("")}><X size={15}/></button></div>}
 {page==="overview"&&<><div className="page-heading"><div><span className="eyebrow">SEU CENTRO DE OPERAÇÕES</span><h1>Visão geral</h1><p className="muted">Acompanhe sua prospecção em um só lugar.</p></div><button className="btn primary" onClick={()=>setPage("search")}><Plus size={16}/> Buscar empresas</button></div><div className="metric-grid"><Metric label="Leads salvos" value={counts.total} caption="Empresas no seu CRM" icon={Building2}/><Metric label="A contatar" value={counts.new} caption="Próxima ação comercial" icon={Users}/><Metric label="Em contato" value={counts.contacted} caption="Contato registrado" icon={MessageCircle}/><Metric label="Em andamento" value={counts.active} caption="Interesse ou negociação" icon={Target}/></div><div className="dashboard-grid"><section className="panel"><PanelTitle title="Leads recentes" detail="Últimas empresas salvas no CRM" action="Ver todos" onAction={()=>setPage("leads")}/>{loading?<Loading/>:leads.length===0?<Empty title="Seu CRM começa aqui" detail="Busque empresas reais e salve as que fizerem sentido." action={()=>setPage("search")}/>:leads.slice(0,6).map(l=><LeadRow key={l.id} lead={l} onClick={()=>setSelected(l)}/>)}</section><section className="panel"><PanelTitle title="Próximos passos" detail="Configure seu fluxo comercial"/><div className="setup-list"><SetupItem n="01" title="Buscar empresas reais" detail="Localização e nicho" onClick={()=>setPage("search")}/><SetupItem n="02" title="Salvar leads no CRM" detail="Deduplicação por empresa" onClick={()=>setPage("leads")}/><SetupItem n="03" title="Entrar em contato" detail="WhatsApp manual e responsável" onClick={()=>setPage("leads")}/><SetupItem n="04" title="Acompanhar negociações" detail="Status e propostas" onClick={()=>setPage("pipeline")}/></div></section></div><div className="bottom-grid"><section className="panel"><PanelTitle title="Pipeline comercial" detail="Distribuição atual dos seus leads" action="Abrir pipeline" onAction={()=>setPage("pipeline")}/><div className="pipeline-summary">{[["Novos",counts.new],["Em contato",counts.contacted],["Negociação",counts.active],["Fechados",counts.closed]].map(([label,count])=><div className="pipeline-stat" key={label as string}><span>{label}</span><strong>{count}</strong></div>)}</div></section><section className="panel"><PanelTitle title="Integrações" detail="Estado dos serviços"/><Integration name="Supabase" connected/><Integration name="Google Places API" connected={backend.placesConfigured()}/></section></div></>}
 {page==="search"&&<><div className="page-heading"><div><span className="eyebrow">AQUISIÇÃO DE CLIENTES</span><h1>Buscar empresas</h1><p className="muted">Encontre negócios reais para sua prospecção.</p></div><span className="source-tag"><Globe2 size={14}/> Google Places</span></div><form className="panel search-form" onSubmit={search}><PanelTitle title="Critérios da busca" detail="Defina uma região e o segmento desejado."/><div className="form-grid"><label>País<select value={country} onChange={e=>setCountry(e.target.value)}><option>Brasil</option><option>Portugal</option><option>Estados Unidos</option><option>Canadá</option><option>Reino Unido</option><option>Outro</option></select></label><label>Estado / região<input value={region} onChange={e=>setRegion(e.target.value)} placeholder="Ex.: Minas Gerais"/></label><label>Cidade *<input required value={city} onChange={e=>setCity(e.target.value)} placeholder="Ex.: Belo Horizonte"/></label><label>Nicho<select value={niche} onChange={e=>setNiche(e.target.value)}>{["Barbearias","Estúdios de tatuagem","Dentistas","Clínicas de estética","Academias","Restaurantes","Salões de beleza","Oficinas mecânicas","Pet shops","Arquitetura","Imobiliárias","Contabilidade","Fotógrafos","Fisioterapeutas","Hotéis e pousadas","Outro nicho"].map(n=><option key={n}>{n}</option>)}</select></label>{niche==="Outro nicho"&&<label>Nicho personalizado<input required value={customNiche} onChange={e=>setCustomNiche(e.target.value)}/></label>}<label>Website informado<select value={websiteFilter} onChange={e=>setWebsiteFilter(e.target.value)}><option value="all">Todos</option><option value="missing">Site não informado no Google</option><option value="present">Com site informado</option></select></label></div>{searchError&&<div className="alert">{searchError}</div>}<div className="form-footer"><p><ShieldCheck size={15}/> Cobertura e limites dependem do provedor.</p><button className="btn primary" disabled={searchBusy}>{searchBusy?<LoaderCircle size={16} className="spin"/>:<Search size={16}/>}{searchBusy?"Buscando...":"Buscar empresas"}<ArrowRight size={15}/></button></div></form><div className="results-heading"><div><h2>Resultados</h2><p>{results.length?results.length+" empresas retornadas pela fonte":"Os resultados reais aparecerão após a busca."}</p></div></div>{searchBusy?<Loading/>:results.length===0?<div className="panel results-empty"><Search size={23}/><strong>Nenhuma busca executada</strong><span>Os resultados não são fictícios e dependem da configuração do Google Places.</span></div>:results.map(p=><PlaceCard key={p.place_id} place={p} saved={leads.some(l=>l.provider_place_id===p.place_id)} saving={savingId===p.place_id} onSave={()=>void save(p)}/>)}</>}
 {(page==="leads"||page==="opportunities")&&<><div className="page-heading"><div><span className="eyebrow">CRM COMERCIAL</span><h1>{page==="leads"?"Meus leads":"Oportunidades"}</h1><p className="muted">Gerencie empresas, contatos e próximos acompanhamentos.</p></div><button className="btn primary" onClick={()=>setPage("search")}><Plus size={16}/> Buscar empresas</button></div><div className="toolbar"><div className="search-input"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar empresa, cidade ou nicho..."/></div><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option>Todos</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><button className="icon-btn" onClick={()=>void loadLeads()}><RefreshCw size={16}/></button></div>{loading?<Loading/>:shownLeads.length===0?<div className="panel results-empty"><Building2 size={23}/><strong>{page==="opportunities"?"Nenhuma oportunidade avaliada":"Nenhum lead encontrado"}</strong><span>{page==="opportunities"?"O score só aparece quando há dados suficientes.":"Busque empresas reais para começar a organizar o CRM."}</span><button className="btn secondary" onClick={()=>setPage("search")}>Buscar empresas <ArrowRight size={14}/></button></div>:shownLeads.map(l=><LeadCard key={l.id} lead={l} onSelect={()=>setSelected(l)} onStatus={s=>void changeStatus(l,s)}/>)}</>}
 {page==="pipeline"&&<><div className="page-heading"><div><span className="eyebrow">GESTÃO DE VENDAS</span><h1>Pipeline comercial</h1><p className="muted">Acompanhe cada lead por etapa de negociação.</p></div><button className="btn secondary" onClick={()=>void loadLeads()}><RefreshCw size={15}/> Atualizar</button></div><div className="pipeline-board">{[["Novos",["Novo","Aguardando contato"]],["Contatados",["Contatado","Aguardando resposta","Sem resposta"]],["Interessados",["Interessado"]],["Propostas",["Proposta enviada","Negociação"]],["Fechados",["Cliente fechado"]],["Perdidos",["Recusado","Não contatar"]]].map(([name,stages])=><section className="pipeline-column" key={name as string}><div className="column-title">{name as string}<span>{leads.filter(l=>(stages as string[]).includes(l.status)).length}</span></div>{leads.filter(l=>(stages as string[]).includes(l.status)).map(l=><article className="pipeline-card" key={l.id}><strong>{l.company_name}</strong><span>{[l.city,l.category].filter(Boolean).join(" · ")}</span><select aria-label="Alterar status" value={l.status} onChange={e=>void changeStatus(l,e.target.value as LeadStatus)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></article>)}</section>)}</div></>}
 {page==="history"&&<section className="panel results-empty"><Activity size={23}/><strong>Histórico comercial</strong><span>O registro detalhado de atividades será expandido na próxima etapa. Nenhuma atividade fictícia é exibida.</span></section>}
 {page==="settings"&&<div className="settings-layout"><section className="panel"><PanelTitle title="Integrações" detail="Serviços necessários"/><Integration name="Supabase" connected={backend.configured()}/><Integration name="Google Places API" connected={backend.placesConfigured()}/><p className="settings-note">A chave privada do Google deve ficar nos secrets da Edge Function, nunca no navegador.</p><a className="btn secondary" href="https://supabase.com/dashboard" target="_blank" rel="noreferrer">Abrir Supabase <ExternalLink size={14}/></a></section><section className="panel"><PanelTitle title="WhatsApp" detail="Contato manual, sem disparos automáticos"/><p className="muted">Abrir o WhatsApp não confirma que a mensagem foi enviada. O status comercial só deve mudar após a confirmação do contato.</p></section></div>}
 </div><footer className="footer"><span>Simply Connect · Prospecção B2B responsável</span><span>Dados privados por workspace</span></footer></main>
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="lead-modal" onClick={e=>e.stopPropagation()}><div className="modal-top"><div><span className="eyebrow">DETALHES DO LEAD</span><h2>{selected.company_name}</h2></div><button className="icon-btn" onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="modal-info">{[selected.address,selected.phone,selected.website,[selected.category,selected.city,selected.region,selected.country].filter(Boolean).join(" · ")].filter(Boolean).map((v,i)=><p key={i}>{i===0?<MapPin size={15}/>:i===1?<MessageCircle size={15}/>:<Globe2 size={15}/>}{v}</p>)}</div><label className="wide-label">Status comercial<select value={selected.status} onChange={e=>void changeStatus(selected,e.target.value as LeadStatus)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="wide-label">Observações<textarea defaultValue={selected.notes??""} placeholder="Notas sobre a empresa..." onBlur={e=>{if(e.target.value!==(selected.notes??""))void backend.updateLead(selected.id,{notes:e.target.value}).then(r=>{if(r.error)setNotice(r.error);else setLeads(cur=>cur.map(l=>l.id===selected.id?{...l,notes:e.target.value}:l))})}}/></label><div className="modal-actions">{selected.phone&&<button className="btn primary" onClick={()=>{const number=selected.phone!.replace(/\D/g,"");if(number.length>=8)window.open("https://wa.me/"+number+"?text="+encodeURIComponent("Olá! Tudo bem? Encontrei sua empresa e gostaria de apresentar uma ideia para melhorar sua presença digital. Posso te mostrar uma sugestão?"),"_blank","noopener,noreferrer");else setNotice("Telefone em formato inválido para WhatsApp.")}}><MessageCircle size={15}/> Abrir WhatsApp</button>}{selected.website&&<a className="btn secondary" href={selected.website} target="_blank" rel="noreferrer">Abrir site <ExternalLink size={14}/></a>}</div><p className="tiny muted">Abrir o WhatsApp não confirma envio da mensagem.</p></section></div>}
 </div>
}
function Brand(){return <div className="brand"><div className="brand-icon"><Command size={19}/></div><span>simply<span className="brand-light">connect</span></span></div>}
function Metric({label,value,caption,icon:Icon}:{label:string;value:number;caption:string;icon:typeof Users}){return <section className="metric-card"><div className="metric-top"><span>{label}</span><Icon size={17}/></div><div className="metric-value">{value.toLocaleString("pt-BR")}</div><div className="metric-caption">{caption}</div></section>}
function PanelTitle({title,detail,action,onAction}:{title:string;detail:string;action?:string;onAction?:()=>void}){return <div className="panel-header"><div><h2>{title}</h2><p>{detail}</p></div>{action&&<button className="text-btn" onClick={onAction}>{action} <ArrowRight size={14}/></button>}</div>}
function Empty({title,detail,action}:{title:string;detail:string;action:()=>void}){return <div className="empty-state"><div className="empty-icon"><Building2 size={20}/></div><strong>{title}</strong><span>{detail}</span><button className="btn secondary" onClick={action}>Buscar empresas <ArrowRight size={14}/></button></div>}
function SetupItem({n,title,detail,onClick}:{n:string;title:string;detail:string;onClick:()=>void}){return <button className="setup-item" onClick={onClick}><span className="setup-number">{n}</span><span className="setup-copy"><strong>{title}</strong><small>{detail}</small></span><ArrowRight size={14}/></button>}
function Integration({name,connected}:{name:string;connected:boolean}){return <div className="integration-row"><span className="integration-mark">{name==="Supabase"?"S":"G"}</span><span className="integration-copy"><strong>{name}</strong><small>{name==="Supabase"?"Banco e autenticação":"Busca de empresas reais"}</small></span><span className={"integration-status "+(connected?"connected":"pending")}>{connected?"Conectado":"Pendente"}</span></div>}
function Loading(){return <div className="panel results-empty"><LoaderCircle className="spin" size={22}/>Carregando dados...</div>}
function LeadRow({lead,onClick}:{lead:Lead;onClick:()=>void}){return <button className="lead-row" onClick={onClick}><div className="company-mark">{lead.company_name.slice(0,1).toUpperCase()}</div><div className="lead-row-copy"><strong>{lead.company_name}</strong><span>{[lead.city,lead.category].filter(Boolean).join(" · ")||"Localização não informada"}</span></div><span className="status-badge">{lead.status}</span><ArrowRight size={14}/></button>}
function LeadCard({lead,onSelect,onStatus}:{lead:Lead;onSelect:()=>void;onStatus:(s:LeadStatus)=>void}){return <article className="lead-card"><button className="lead-card-main" onClick={onSelect}><div className="company-mark">{lead.company_name.slice(0,1).toUpperCase()}</div><div className="lead-card-copy"><strong>{lead.company_name}</strong><span>{[lead.city,lead.region,lead.country].filter(Boolean).join(", ")}</span><small>{lead.category??"Categoria não informada"}</small></div></button><div className="lead-card-bottom"><span className="status-badge">{lead.status}</span><select aria-label="Status comercial" value={lead.status} onChange={e=>onStatus(e.target.value as LeadStatus)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><button className="icon-btn" onClick={onSelect}>…</button></div></article>}
function PlaceCard({place,saved,saving,onSave}:{place:PlaceResult;saved:boolean;saving:boolean;onSave:()=>void}){return <article className="place-card"><div className="place-card-main"><div className="company-mark"><Building2 size={17}/></div><div className="place-copy"><strong>{place.name}</strong><span>{[place.category,place.city,place.region].filter(Boolean).join(" · ")}</span><small>{place.address??"Endereço não informado"}</small><div className="place-meta">{place.rating!==null&&<span>★ {place.rating.toFixed(1)}{place.rating_count!==null?" ("+place.rating_count+")":""}</span>}{place.website?<a href={place.website} target="_blank" rel="noreferrer">Abrir site <ExternalLink size={12}/></a>:<span>Site não informado no Google</span>}{place.phone&&<span>{place.phone}</span>}</div></div></div><div className="place-actions">{place.maps_url&&<a className="btn secondary small-btn" href={place.maps_url} target="_blank" rel="noreferrer"><MapPin size={14}/> Maps</a>}<button className={"btn small-btn "+(saved?"secondary":"primary")} disabled={saved||saving} onClick={onSave}>{saved?<Check size={14}/>:saving?<LoaderCircle size={14}/>:<Plus size={14}/>}{saved?"Já adicionada":saving?"Salvando":"Adicionar lead"}</button></div></article>}
function Setup(){return <div className="auth-shell"><section className="auth-card setup-card"><Brand/><div className="empty-icon"><Settings2 size={22}/></div><h1>Configure o backend</h1><p className="muted">A aplicação está preparada para o Supabase, mas as variáveis de ambiente ainda não foram definidas.</p><div className="env-list"><code>VITE_SUPABASE_URL</code><code>VITE_SUPABASE_ANON_KEY</code></div><p className="tiny muted">Configure também GOOGLE_PLACES_API_KEY nos secrets da Supabase Edge Function. Não use prefixo VITE_ para chaves privadas.</p><a className="btn secondary full" href="https://supabase.com/dashboard" target="_blank" rel="noreferrer">Abrir Supabase <ExternalLink size={15}/></a></section></div>}
